config/routes.rb
Rails.application.routes.draw do
  #devise_for :patients
  #devise_for :doctors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :patients, :path_names => {:sign_up => "sign_up"},:controllers => {:registrations => "patients/registrations"}
  devise_for :doctors, :path_names => {:sign_up => "sign_up"},:controllers => {:registrations => "doctors/registrations"}
  resources :doctors
  resources :patients
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :doctor_categories
  resources :time_slots
  get 'cities/', to: 'doctors#cities'
end

app/models/doctor_category.rb
class DoctorCategory < ActiveRecord::Base
  
  # Associations
  has_many :doctors
  validates :name, presence: true
  validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/


  has_attached_file :avatar, styles: { large: "520x520>", medium: "300x300>", small: "256x256>", thumb: "100x100>", tiny: "50x50>" }, default_url: ":style/missing_avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/doctor_categories_controller.rb
class DoctorCategoriesController < ApplicationController
	before_action :set_doctor_category, only: [:show, :edit, :update, :destroy]
  before_action :set_doctors, only: [:show]

  def index
    @doctor_categories = DoctorCategory.all
  end

  def show
    if @doctors and !params[:state].blank? and !params[:city].blank?
      @doctors = @doctors.where(state:params[:state],city:params[:city])
    end
  end

  def new
  	@doctor_category = DoctorCategory.new
  end

  def edit
  end

  def create
    @doctor_category = DoctorCategory.new(doctor_category_params)

    respond_to do |format|
      if @doctor_category.save
	      format.html { redirect_to @doctor_category, notice: 'doctor category uploaded'}
	      format.json { render :show, status: :created, location: @doctor_category }
      else
        format.html { render :new }
        format.json { render json: @doctor_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @doctor_category.update(doctor_category_params)
        format.html { redirect_to @doctor_category, notice: 'doctor category was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_category }
      else
        format.html { render :edit }
        format.json { render json: @doctor_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @doctor_category.destroy
    respond_to do |format|
      format.html { redirect_to doctor_categories_url, notice: 'doctor category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_category
      @doctor_category = DoctorCategory.find(params[:id])
    end

    def set_doctors
       @doctors =  @doctor_category.doctors.active
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_category_params
      params.require(:doctor_category).permit(:name, :avatar)
    end
    
end

app/helpers/doctor_categories_helper.rb
module DoctorCategoriesHelper
end

app/views/doctor_categories/_form.html.erb
<%= form_for(@doctor_category, :html => {multipart:true}) do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control' %>
  </div>

   <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :class => 'button right' %>
  </div>

<% end %>

app/views/doctor_categories/edit.html.erb
<div class="authform">
<div class="row">
<div class="col-md-6"><h2>Edit Doctor Category</h2></div>
<div class="col-md-2 col-md-offset-4" ><%= link_to 'Back', doctor_categories_path %></div>
</div>
<br>
<%= render 'form' %>
</div>

app/views/doctor_categories/index.html.erb
<% if user_signed_in? %>
  <div  align="center" style="width:75% !important;">  
   <div class="container">
   <div class="row">
   <div class="col-md-2 col-md-offset-10" >
   <%= link_to 'New Doctor Category', new_doctor_category_path %>
    </div>
   </div>
   <p id="notice"><%= notice %></p>

  <h1>Listing Doctors Category</h1>
  <br><br>
  <table class="table" style="width:50%">
    <thead>
      <tr>
        <th colspan="2">Avatar</th>
        <th colspan="2">Name</th>
        <th >Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @doctor_categories.each do |doctor_category| %>
        <tr >
        <td colspan="2">
        <% if doctor_category.avatar.present? %>
          <%= image_tag doctor_category.avatar.url(:tiny) %>
        <% else %>
          <%= image_tag("missing_doctor_category_avatar.png",size: "50x50") %>
        <% end %>
        </td>
        <td colspan="2"><%=doctor_category.name.capitalize %></td>
        <td style="width:10%"><%= link_to 'Show', doctor_category %></td>
        <td style="width:10%"><%= link_to 'Edit', edit_doctor_category_path(doctor_category) %></td>
        <td style="width:10%"><%= link_to 'Destroy', doctor_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  </div>
  </div>
<%end%>

app/views/doctor_categories/new.html.erb
<div class="authform">
<div class="row">
<div class="col-md-6"><h2>New Doctor Category</h2></div>
<div class="col-md-2 col-md-offset-4" ><%= link_to 'Back', doctor_categories_path %></div>
</div>
<%= render 'form' %>
</div>

app/views/doctor_categories/show.html.erb
<div class="container">
  <form class="form-inline" role="form">
    <div class="form-group">
      <%= form_tag("/doctor_categories/#{params[:id]}", method: "get") do %>
      <div class="field" >
        <%= select_tag "state", options_from_collection_for_select(CS.states(:in),:first, :last) , :prompt => '--Select State--'%>
      </div>
    </div>

    <div class="form-group">
      <div class="field" id='home-state-cities' >
        <%= select_tag "city", @cities, :prompt => '--Select City--'%>
      </div>
    </div>
    &nbsp<%= button_tag(type: "submit", class: "btn btn-success") do %>
    Search <i class="icon-repeat"></i>
<% end %>
  <% end %>

  <ul class="nav pull-right">
  <div class="dropdown">
  
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Doctor Category
    <span class="caret"></span></button>
    <ul class="dropdown-menu">
      <% DoctorCategory.all.each do |dc|%>
        <li><%= link_to dc.name, doctor_category_path(dc.id) %></li>
        <% end %>

    </ul>
    </div>
    </ul>

    <h2>Listing Doctors for <%= @doctor_category.name%></h2>
    <% @doctors.all.each do |doctor| %>
	     <ul class="list-group">
	        <li class="list-group-item"><span class="badge"></span> 
	        <%= link_to doctor.name.capitalize, doctor %><br />
	        <%= "#{doctor.experience} years of experience"%><br />
	        <%= "Working at #{doctor.hospital_name}" %><br />
	        </li>
	     </ul>
    <% end %>

</div>
</form>


	<!-- <div class="container">
	  <h2>Doctors</h2>
	  <% @doctors.all.each do |doctor| %>
		  <button type="button" class="btn btn-info" data-toggle="collapse" 
		  data-target= "#demo_#{doctor.id.to_s}" %><%= doctor.name %></button>
		  <div id="demo_#{doctor.id}" class="collapse">
			    <%= link_to doctor.name.capitalize, doctor %><br />
			    <%= "#{doctor.experience} years of experience"%><br />
			    <%= "Working at #{doctor.hospital_name}" %><br />
		  </div>
		  <br />
	  <%end%>
	</div> -->

<%#= link_to 'Edit', edit_doctor_category_path(@doctor_category) %> 
<%#= link_to 'Back', doctor_categories_path data-target="#demo#{doctor.id}"> %>


<script type="text/javascript">
  

  $(document).ready(function(){ 
    $("#state").click(function(){

        var state1 = $('#state').val();
        $.ajax({
          method: "GET",
          url: "/cities",
          data: { state:state1 }
        })

        .done(function( cities ) {
          var cityElm=$("#home-state-cities")
          var optValues=""
          cityElm.css("display","block")

          for (i = 0; i < cities.length; i++) { 
            optValues += "<option>" + cities[i] + "</option>";
          }
          cityElm.html("<select name=city>" + optValues+ "</select>")  
        });
      } 
    );


  });
    
</script>