config/routes.rb
Rails.application.routes.draw do
  #devise_for :patients
  #devise_for :doctors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :patients, :path_names => {:sign_up => "sign_up"},:controllers => {:registrations => "patients/registrations"}
  devise_for :doctors, :path_names => {:sign_up => "sign_up"},:controllers => {:registrations => "doctors/registrations"}
  resources :doctors
  resources :patients
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :doctor_categories
  resources :time_slots
  get 'cities/', to: 'doctors#cities'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if doctor_signed_in? %>
  <%= link_to 'Edit Account', edit_doctor_registration_path, class: 'navbar-brand' %>
  <%= link_to 'Your Details', edit_doctor_path(current_doctor.id), class: 'navbar-brand' %>
  <%= link_to 'Sign out', destroy_doctor_session_path, :method=>'delete', class: 'navbar-brand' %>
<% elsif user_signed_in? %>
  <%= link_to 'Admin', '/admin', class: 'navbar-brand' %>
  <%= link_to 'Doctor Categories', doctor_categories_path, class: 'navbar-brand' %>
  <%= link_to 'Doctors', doctors_path, class: 'navbar-brand' %>
  <%= link_to 'List Admins', users_path, class: 'navbar-brand' %>
  <%= link_to 'Edit Account', edit_user_registration_path, class: 'navbar-brand' %>
  <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'navbar-brand' %>
<% elsif patient_signed_in? %>
  <%= link_to 'Edit Account', edit_patient_registration_path, class: 'navbar-brand' %>
  <%= link_to 'Your Details', edit_patient_path(current_patient.id), class: 'navbar-brand' %>
  <%= link_to 'Sign out', destroy_patient_session_path, :method=>'delete', class: 'navbar-brand pull-right' %>
<% else %>
  <%#= link_to 'Admin Sign in', new_user_session_path, class: 'navbar-brand' %>
  <%#= link_to 'Admin Sign up', new_user_registration_path, class: 'navbar-brand' %>
  <%= link_to 'Doctor Sign in', new_doctor_session_path, class: 'navbar-brand' %>
  <%= link_to 'Doctor Sign up', new_doctor_registration_path, class: 'navbar-brand' %>
  <%= link_to 'Patient Sign in', new_patient_session_path, class: 'navbar-brand' %>
  <%= link_to 'Patient Sign up', new_patient_registration_path, class: 'navbar-brand' %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%#= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Doctor" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Doctor" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>